[package]
name = "recreate"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
clap = { version = "4.5.18", features = ["derive"] }
image = "0.25.2"
image-effects = "0.1.0"
kmeans_colors = "0.6.0"
palette = "0.7.6"
rand = "0.8.5"
rayon = "1.10.0"
